### ISSUE TITLE
Vault Agent doesn't appear to re-read TLS certificates for auto_auth.

### ISSUE THREAD

**Issue by the-maldridge** [hashicorp/vault#16266]
**Describe the bug**
When using extremely short lived certificates for TLS auto auth the agent doesn't appear to correctly and completely reread the certificates when they are changed on disk.  This breaks the authentication flow when the certificates are updated by external automation.

**To Reproduce**
1. Configure a vault instance with TLS auth, and an agent to auto_auth against it.  In my testing I created a role that just grants the `default` policy to the token.
2. Rotate the certificate on disk to a still valid, but new cert.

**Expected behavior**
I expect this to work, and it does not appear to.  My logs on my test machines are all full of error messages of the form:

```
2022-07-09T14:11:36Z vault-agent 2022-07-09T14:11:36.490Z [ERROR] auth.handler: error authenticating: error="Put \"https://node1.lan:8200/v1/auth/resin_fleet/login\": x509: certificate has expired or is not yet valid: current time 2022-07-09T14:11:36Z is after 2022-07-09T06:58:59Z" backoff=4m30.59s
```

**Environment:**
* Vault Server Version (retrieve with `vault status`):

```
$ vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.10.0
Storage Type    file
Cluster Name    vault-cluster-372f744f
Cluster ID      ea6d84ab-42cf-c7e5-6a5f-85a348d49ee8
HA Enabled      false
```

* Vault CLI Version (retrieve with `vault version`):

```
Vault v1.10.0 (7738ec5d0d6f5bf94a809ee0f6ff0142cfa525a6)
```

* Server Operating System/Architecture:

Both agent and server are coming from the official vault docker image running on x86_64 architecture.

Vault server configuration file(s):

```hcl
ui = true
cat: read error: Is a directory
cat: read error: Is a directory
node1:/# cat /etc/vault/* /run/config/vault/*
ui = true
listener "tcp" {
  address = "0.0.0.0:8200"

  tls_cert_file = "/run/config/step/node.crt"
  tls_key_file = "/run/config/step/node.key"
  
  telemetry {
    unauthenticated_metrics_access = true
    promtheus_retention_time = "240s"
  }
}
storage "file" {
  path = "/var/persist/vault/"
}
```

```hcl
vault {
  address = "https://node1.lan:8200"
  ca_cert = "/run/config/step/root_ca.crt"
}

auto_auth {
  method {
    type = "cert"
    mount_path = "auth/resin_fleet"

    config = {
      ca_cert = "/run/config/step/root_ca.crt"
      client_cert = "/run/config/step/node.crt"
      client_key = "/run/config/step/node.key"
    }
  }

  sink {
    type = "file"

    config = {
      path = "/tmp/.host-token"
    }
  }
}
```

```hcl
resource "vault_auth_backend" "fleet_auth" {
  path = "resin_fleet"
  type = "cert"
  
  description = "Fleet Certificate Authentication"
}

resource "vault_cert_auth_backend_role" "roles" {
  for_each = var.vault_role_policy_map
  
  name           = each.key
  certificate    = file(var.vault_cert_ca_file)
  backend        = vault_auth_backend.fleet_auth.path
  token_ttl      = 300
  token_max_ttl  = 600
  token_policies = each.value
}
```

**Additional context**
The first few renews appear to work, but then the renewal loop gets into this state where the certificate is no longer valid.  I'm exaggerating the time spans while testing by setting the certificate maximum lifetime to 10 minutes, which causes external automation to attempt to renew them every ~6 minutes.  Part of me wonders if this is a problem with the two renewal windows, between the cert and the token phasing in and out with each other.

**Comment by the-maldridge** [comment]
As near as I am able to tell, this was a combination issue with vault itself not reloading TLS which I fixed by upgrading to a current version, and an issue with the agent not renewing by default, which was fixed by kicking the agent from the process that renews the machine certificates.

**Comment by ArchiFleKs** [comment]
Same issue [here](https://github.com/hashicorp/vault-k8s/issues/394). I would expect Vault agent to be able to reload in case files change

**Comment by ArchiFleKs** [comment]
Any update on this ? This is quite an annoying issue for short lived certificates

**Comment by kencx** [comment]
Still facing this issue in v1.13.1, but it seems #19002 aims to fix this.
