### ISSUE TITLE
1.19.0 Breaking Bug: AWS STS 400 Error: {"errors":["number of regions does not match number of endpoints"]}

### ISSUE THREAD

**Issue by cmmarslender** [hashicorp/vault#29869]
**Describe the bug**
After updating to 1.19.0, when calling an aws sts endpoint, we now receive `{"errors":["number of regions does not match number of endpoints"]}`. These calls all used to work just fine. 

The new error was introduced in this PR https://github.com/hashicorp/vault/pull/29051

The AWS backend is configured like:

```
resource "vault_aws_secret_backend" "aws-chia" {
  access_key = var.chia_aws_access_key_id
  secret_key = var.chia_aws_secret_access_key
  path       = "aws"
}
```

You will note that in this config, no sts endpoint is set at all since that is supposed to be an optional parameter, so it was previously using whatever the default was. If I'm following the flow correctly, `&endpoint` was likely nil at this point https://github.com/hashicorp/vault/blob/v1.18.5/builtin/logical/aws/client.go#L96 and AWS SDK probably had a fallback.

On the new PR / 1.19.0:

fallback region is specifically set to us-east-1 in the client.go file https://github.com/hashicorp/vault/blob/c937b3e2546bb40606b4cba1d1a5a1a53bfc2840/builtin/logical/aws/client.go#L36 and then later, if no region(s) were otherwise set, this hardcoded default is added to the regions list https://github.com/hashicorp/vault/blob/c937b3e2546bb40606b4cba1d1a5a1a53bfc2840/builtin/logical/aws/client.go#L96

No such logic exists for endpoints - if no endpoints are set in config at all (which is not documented as required), the endpoints will be an empty list.

The combination of these two factors results in this error always firing for very simple sts configurations, since endpoints will be 0 and regions will always be at least 1. (I have not tried editing the code and trying a new build, but this is the only explanation I see at first glance that explains the issue)

**Comment by cmmarslender** [comment]
Tried to add a region and endpoint in the UI to un-break this, and now I get a new error: `{"errors":["could not obtain sts client"]}`

The config looks like the following when getting this new error

![Image](https://github.com/user-attachments/assets/3894279b-923a-4999-8a88-da19de19baae)

**Comment by cmmarslender** [comment]
Strangely enough, if I change the endpoint to the global endpoint (`sts.amazonaws.com` - which is supposedly just in `us-east-1`), it works fine, even with the region still set to `us-west-2`.

Removing the endpoint from the config in the UI breaks it again.

**Comment by heatherezell** [comment]
Thank you so much for this detailed report! I've alerted our engineering teams, and I hope to have something for you soon. Really appreciate it. :)

**Comment by F21** [comment]
Hoping this is fixed soon. This is currently blocking us after upgrading to 1.19.0.

**Comment by pmarshallase** [comment]
I ran into the same and was able to get round the issue with:
vault write aws/config/root sts_endpoint=sts.eu-west-2.amazonaws.com sts_region=eu-west-2

**Comment by gautamg795** [comment]
We ran into this as well; had to set the IAM endpoint to `iam.amazonaws.com` as well to get things unblocked

**Comment by gautamg795** [comment]
If I understand correctly, this will break the AWS secrets engine for anyone upgrading to 1.19.0 from a preexisting "default" setup (it's unclear to me if this breaks for newly-added secrets engines on 1.19.0 as well.)

As such, the release should probably have a prominent note somewhere that it's broken and users should not update if they use the AWS secrets engine?

**Comment by asvinours** [comment]
I've upgraded Vault to 1.19.1 and still facing an STS issue.

I've tried setting the region to `us-east-1` with an empty IAM and STS endpoint config, a set region with both set STS and IAM endpoints, both sets endpoints with no region and a few other combination of global or region endpoints value and region set and unset and I always get a `could not obtain sts client` error.

**Comment by luanaBanana** [comment]
We faced this issue with `1.19.2` as well.  For us it helped to set the ENV VAR `AWS_REGION`

It seems like the region set through the CLI does not work. We tried it like this and also with the `sts_endoint` set and it didnt work: 

```
$ vault read aws_earth/config/root
Key                           Value
---                           -----
access_key                    XX
disable_automated_rotation    false
iam_endpoint                  n/a
identity_token_audience       n/a
identity_token_ttl            0s
max_retries                   -1
region                        eu-central-2
role_arn                      n/a
rotation_period               0s
rotation_schedule             n/a
rotation_window               0
sts_endpoint                  n/a
sts_fallback_endpoints        <nil>
sts_fallback_regions          <nil>
sts_region                    n/a
```

As soon as we added the ENV VAR it worked.

**It would have been really important to add this bug to the known issues list to prevent debugging. Could you please add it in order to prevent other users to face this issue as well.**
