### ISSUE TITLE
Vault Crashes OOM

### ISSUE THREAD

**Issue by ars05** [hashicorp/vault#4803]
**Describe the bug**
When a Vault node in cluster of 6 with consul back-end becomes leader, the CPU Load and Memory increases to the point is crashes because of OOM.

**To Reproduce**
Vault node becomes leader and is crashing with:
```fatal error: runtime: out of memory```

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`):
Key             Value
---             -----
Seal Type       shamir
Sealed          false
Total Shares    5
Threshold       3
Version         0.10.1
Cluster Name    vault-cluster-
Cluster ID      
HA Enabled      true
HA Cluster      https://
HA Mode         active

* Server Operating System/Architecture:

Docker version 18.03.1-ce, build 9ee9f40
4.14.48-coreos-r2

Vault server configuration file(s):
```hcl
{"storage": {"consul": {"address": ":8500", "path": "vault", "token": "${consul_token}" }}, "listener": { "tcp": { "address": "0.0.0.0:443", "tls_cert_file": "/vault/certs/tls.crt", "tls_key_file": "/vault/certs/tls.key" }}, "disable_cache": "true", "disable_mlock": "true", "ui": "true"}
```

**Additional context**
Consul back-end : Consul 1.1.0
Crash log:  [vault_crash.log](https://github.com/hashicorp/vault/files/2119290/vault_crash.log)
Prometheus Monitoring Graph: 
![vault](https://user-images.githubusercontent.com/18533856/41660090-f4730c4a-7492-11e8-8c94-aa800b3cfc52.PNG)

**Comment by jefferai** [comment]
It sounds like you have a huge number of leases, so when Vault is loading them when a node becomes active, you OOM. Probably you need to increase memory to get past the immediate issue, and then figure out why you have so many leases. (Running trace mode on logs will have the lease loading print out a total and running load count.)

**Comment by ars05** [comment]
@jefferai - Thanks for your response, the total number of leases we have is around 100

**Comment by jefferai** [comment]
You could try upgrading to 0.10.3, although I doubt there's anything relevant (but it's a good idea anyways).

Depending on what the issue is, based on your log, 0.10.2 may in fact help. We've fixed issues in 0.10.1 and 0.10.2 related to revocation logic.

Can you get total counts of items in Consul under sys/expire/id and sys/token/id?

**Comment by ars05** [comment]
Thanks for you suggestions, Infact I was just reviewing the changes in 0.10.3 
121 under sys/expire/id
59 under sys/token/id

**Comment by jefferai** [comment]
Please let us know if the problem persists under 0.10.2/0.10.3.

**Comment by ars05** [comment]
The problem persist on  0.10.2 as well as on 0.10.3
![vault-10-3](https://user-images.githubusercontent.com/18533856/41672934-29491462-74b3-11e8-891d-16a03f7cb64d.PNG)

**Comment by jefferai** [comment]
Can you get another crash log from 0.10.3? Since the logic has changed significantly it would be good to know the current stack trace.

Also, is there a reason you are running with disable_cache set to true? Does this issue go away if you remove that config option?

**Comment by ars05** [comment]
I'm waiting for 0.10.3 docker image to be available. disable_cache is set to false (default value)
``` [DEBUG] expiration: leases collected: num_existing=117 ```
The memory issue is still persist.
![disable_cache](https://user-images.githubusercontent.com/18533856/41674464-f536af90-74b7-11e8-984f-ebbe6750ec64.PNG)

**Comment by jefferai** [comment]
> {"storage": {"consul": {"address": ":8500", "path": "vault", "token": "${consul_token}" }}, "listener": { "tcp": { "address": "0.0.0.0:443", "tls_cert_file": "/vault/certs/tls.crt", "tls_key_file": "/vault/certs/tls.key" }}, "disable_cache": "true", "disable_mlock": "true", "ui": "true"}

It's set to `true`...

**Comment by ars05** [comment]
Changed it to "false" after your last comment, then restarted all the nodes, the graph in my previous comment is the leader with "disable_mlock": "false"

**Comment by ars05** [comment]
Vault 0.10.2 crash log:
[vault-0-10-2.log.txt](https://github.com/hashicorp/vault/files/2123582/vault-0-10-2.log.txt)

**Comment by briankassouf** [comment]
Could you also post the full vault server logs with any sensitive values redacted? It seems the crash is happening while trying to revoke a lease. It would be helpful to see any lease revocation errors from the logs.

**Comment by briankassouf** [comment]
@ars05 Did anything change with your underlying datastore? Vault being unable to decrypt the data can mean the data changed out from under it. Perhaps from a bad consul restore. 

That being said it shouldn't cause a OOM. The full logs would be helpful to determine what's being loaded into memory and if you got into some kind of loop attempting to revoke this lease.

**Comment by briankassouf** [comment]
@ars05 I don't see anything suspicious in the log file, what calls are clients making during the time the memory is growing?

**Comment by briankassouf** [comment]
Also were you ever able to try the 0.10.3 docker container to see if it was fixed in that version?

**Comment by briankassouf** [comment]
@ars05 Are you still experiencing this OOM and could describe the access patterns and what auth/secret mounts you are using?

**Comment by ars05** [comment]
@briankassouf - this issue still persists. When a node becomes Active, the memory usage increases to the point which crashes with **fatal error: runtime: out of memory** and another node in the cluster becomes active and goes through he same cycle. 

In total we have 25 secret engines enabled. 5 AWS, 1 Consul, 5 secrets, 1 SSH, 13 PKI
10-15 SRE Engineers access to Vault (mostly through UI) AD/LDAP integration is enabled.
In term of Authentication Methods, 3 Kubernetes clusters, ldap, approle and token (by default) is enabled/configured.

**Comment by kalafut** [comment]
@ars05 I just pushed a branch off of 0.10.3 that enables some basic memory profiling: https://github.com/hashicorp/vault/tree/profile-0.10.3 . Are you able to build from source?

This version will save memory stats files in `$TMPDIR/vaultprof/` every 5 minutes. If you can run with this version through the event and send us a zip of the `vaultprof` folder, we should be able to get a better idea of what is using so much memory.

**Comment by kalafut** [comment]
The profiling will be on regardless of active status. The log message is at the DEBUG level, so you'd need to start with the vault binary with `-log-level=debug` to see a message like this appear in the log stream:
```
2018-09-04T11:01:22.314-0700 [DEBUG] wrote memory profile: filename=/var/folders/yy/kf718y9x41g40ncf8s29mshh0000gn/T/vaultprof/20180904_180122.pprof
```
But debug is not required for the profiling to actually occur. Did you check `$TMPDIR` for a `vaultprof` folder, and some files therein?

**Comment by ars05** [comment]
@kalafut - please find the pprof files attached. 
[vaultprof.zip](https://github.com/hashicorp/vault/files/2360299/vaultprof.zip)

**Comment by kalafut** [comment]
@ars05 Thanks, these were pretty useful. Based on them, I'd like to review the structure of some token data in Consul. Can you please export and provide the list of keys under vault/sys/token/parent, e.g.:

`curl http://<consul address>/v1/kv/vault/sys/token/parent\?keys > out.json` 

This list will only contain hashed UUID paths like `"vault/sys/token/parent/10e62d82c8982d247b64c8b17c44c24e7b6d4d5e/6da14c90b428e2f7c8140c44c14d836d0e0af4e6"`. If you wish you can email the output to me directly: jkalafut@hashicorp.com

**Comment by ars05** [comment]
@kalafut - Thanks, I sent you an email with the list of keys.

**Comment by kalafut** [comment]
We were able to create an abnormal key state (a parent/child cycle) that would result in ever growing memory use that is similar to the profiles you sent earlier. The keys you provided had this problem state as well.

A PR (https://github.com/hashicorp/vault/pull/5335) is up to handle such cycles correctly.

**Comment by ars05** [comment]
This issue is resolved.
![vault-0-11-3](https://user-images.githubusercontent.com/18533856/46803087-23b95f00-cd57-11e8-95ef-66bdbbe1db47.png)

**Comment by kalafut** [comment]
@ars05 Excellent news!
