### ISSUE TITLE
GitHub Backend Acceptance Tests Fail: "[ERR] core: unable to look up sys view for login path"

### ISSUE THREAD

**Issue by larryboymi** [hashicorp/vault#651]
Prior to pulling today's source, I was able to get auth backend acceptance tests to run and pass the login step. Now on each login step I get ```"[ERR] core: unable to look up sys view for login path"``` with the request/response for logging in printed. I'm new to the source so trying to figure out why that is, but it happens for me in ```github``` & ```cert``` so far, guessing other auth backends as well.

Env vars used to test (with token x'd out):

<pre>
GITHUB_ORG=larryboymi-testing
TF_ACC=1
GITHUB_TOKEN=xxx
GITHUB_BASEURL=https://api.github.com
</pre>

Test output:

<pre>2015/09/29 10:37:56 [INFO] core: mounted 'mnt/' type: test
2015/09/29 10:37:56 [WARN] Executing test step 1
2015/09/29 10:37:56 [WARN] Executing test step 2
2015/09/29 10:37:56 [WARN] Executing test step 3
2015/09/29 10:37:56 [WARN] Executing test step 4
2015/09/29 10:37:57 [ERR] core: unable to look up sys view for login path(request: *logical.Request{Operation:"write", Path:"mnt/login", Data:map[string]interface {}{"token":"xxx"}, Storage:logical.Storage(nil), Secret:<nil>, Auth:<nil>, Connection:(*logical.Connection)(nil), ClientToken:"", DisplayName:"", MountPoint:""}, response: &logical.Response{Secret:<nil>, Auth:*logical.Auth{LeaseOptions:logical.LeaseOptions{TTL:0, GracePeriod:0, Renewable:false, Increment:0, IssueTime:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, InternalData:map[string]interface {}(nil), DisplayName:"mnt-larryboymi", Policies:[]string{"root"}, Metadata:map[string]string{"username":"larryboymi", "org":"larryboymi-testing"}, ClientToken:""}, Data:map[string]interface {}(nil), Redirect:""})
2015/09/29 10:37:57 [WARN] Requesting RollbackOperation
	testing.go:216: Failed step 4: internal error</pre>

**Comment by larryboymi** [comment]
<pre>2015/09/29 10:37:56 [INFO] core: mounted 'mnt/' type: test
2015/09/29 10:37:56 [WARN] Executing test step 1
2015/09/29 10:37:56 [WARN] Executing test step 2
2015/09/29 10:37:56 [WARN] Executing test step 3
2015/09/29 10:37:56 [WARN] Executing test step 4
2015/09/29 10:37:57 [ERR] core: unable to look up sys view for login path(request: *logical.Request{Operation:"write", Path:"mnt/login", Data:map[string]interface {}{"token":"xxx"}, Storage:logical.Storage(nil), Secret:<nil>, Auth:<nil>, Connection:(*logical.Connection)(nil), ClientToken:"", DisplayName:"", MountPoint:""}, response: &logical.Response{Secret:<nil>, Auth:*logical.Auth{LeaseOptions:logical.LeaseOptions{TTL:0, GracePeriod:0, Renewable:false, Increment:0, IssueTime:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, InternalData:map[string]interface {}(nil), DisplayName:"mnt-larryboymi", Policies:[]string{"root"}, Metadata:map[string]string{"username":"larryboymi", "org":"larryboymi-testing"}, ClientToken:""}, Data:map[string]interface {}(nil), Redirect:""})</pre>

**Comment by jefferai** [comment]
This is probably due to the backend not properly calling the framework Setup function. I can fix this soon.

**Comment by larryboymi** [comment]
Thanks, glad to hear it's not something I did wrong. I'm new to Go as well as creating these backends but I'm trying to make one modeled after these, and running the tests was something I was doing as a sanity check.

**Comment by jefferai** [comment]
Prior to the 0.3 dev cycle calling the Setup function was recommended but
if you didn't nothing bad happened. It's now required, and the code in the
backend is fine (but needs to be updated) but in the tests can fail even if
the backend works okay.

Thanks for the report!

**Comment by sherzberg** [comment]
I have hit this as well in a custom auth backend we have. What `Setup` function are you talking about? Or where was this change made? Upgrading our fork to the latest from `0.3` code I get this same error in our tests.

**Comment by jefferai** [comment]
The setup function is in logical.Framework. All backends in non-test scenarios receive a DynamicSystemView from the core and call the Setup function in their factory, but not all acceptance tests have been fixed to do so.

Take a look at https://github.com/hashicorp/vault/commit/59a3f6b5d2b3299c63e9112c28526c7b8a84961c -- by making similar changes it should fix your issue.

**Comment by jefferai** [comment]
Fixed in https://github.com/hashicorp/vault/commit/59a3f6b5d2b3299c63e9112c28526c7b8a84961c

**Comment by sherzberg** [comment]
Thanks! This helped me fix my issue.

**Comment by larryboymi** [comment]
This fixes it for OAuth, but I'm getting the same error on the ```cert``` acceptance test.

**Comment by jefferai** [comment]
It's a per backend solution, so needs to be fixed there too then.

Unfortunately most backends start with a lot of copypasta...

**Comment by larryboymi** [comment]
Gotcha...I know I could help by submitting a merge request, but I'm still getting my feet wet.

**Comment by jefferai** [comment]
No worries! This is easy for me to fix (but currently traveling).

We do appreciate the reports... we constantly run unit tests on the main
code but backends are so setup specific (and can require external accounts
or resources that can cost money) that we usually don't run their
acceptance tests except when we change backend code. So reports from users
are very valuable.
